export enum ActionType {
    FETCHING = "_FETCHING",
    SUCCESS = "_SUCCESS",
    ERROR = "_ERROR",
    FORM = "FORM",
    HANDLE_EMAIL = "HANDLE_EMAIL",
    HANDLE_RADIO = "HANDLE_RADIO",
    HANDLE_SELECT = "HANDLE_RADIO",
    HANDLE_TELEPHONE = "HANDLE_TELEPHONE",
    HANDLE_JSON_VISIBILITY= "HANDLE_JSON_VISIBILITY"
}